/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Java_GUI_Form;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Vector;

/**
 *
 * @author figueroaf
 */

public class Java_GUI_Form extends javax.swing.JPanel {

    private static final String username = "project";
    private static final String password = "project";
    private static final String dataConn = "jdbc:mysql://localhost:3306/playerstats";

    Connection sqlConn = null;

    PreparedStatement pst = null;

    ResultSet rs = null;

    int q, i, id, deleteItem;

    public Java_GUI_Form() {
        initComponents();
            upDateDB();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //==============================Function=========================================
    
    public void upDateDB() {

        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pst = sqlConn.prepareStatement("select * from PlayerStats");
            rs = pst.executeQuery();
            ResultSetMetaData stData = rs.getMetaData();
            q = stData.getColumnCount();

            DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
            RecordTable.setRowCount(0);

            while (rs.next()) {
                Vector columnData = new Vector();

                for (i = 1; i <= q; i++) {
                    columnData.add(rs.getString(1)); // Assuming Player is the first column
                    columnData.add(rs.getString(2)); // Assuming Number is the second column
                    columnData.add(rs.getInt(3)); // Assuming FTA is the third column
                    columnData.add(rs.getInt(4)); // Assuming FTM is the fourth column
                    columnData.add(rs.getFloat(5)); // Assuming FT_Percentage is the fifth column
                    columnData.add(rs.getInt(6)); // Assuming ThreePointAttempts is the sixth column
                    columnData.add(rs.getInt(7)); // Assuming ThreePointMade is the seventh column
                    columnData.add(rs.getFloat(8)); // Assuming ThreePoint_Percentage is the eighth column
                }
                RecordTable.addRow(columnData);
            }
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    //==============================End Function=========================================
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jtxtNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtFTA = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtFTM = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtFT_Percentage = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtxtThreePointAttempts = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jtxtThreePointMade = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtxtThreePoint_Percentage = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtxtPlayer = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jbtnUpdate = new javax.swing.JButton();
        jbtnAdd = new javax.swing.JButton();
        jbtnReset = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnExit = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jtxtNumber.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jtxtNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNumberActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 380, -1));

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel3.setText("FTA");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jtxtFTA.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jPanel2.add(jtxtFTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 380, -1));

        jLabel4.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel4.setText("FTM");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jtxtFTM.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jtxtFTM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFTMActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtFTM, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 380, -1));

        jLabel5.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel5.setText("FT_Percentage");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jtxtFT_Percentage.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jtxtFT_Percentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFT_PercentageActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtFT_Percentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 380, -1));

        jLabel6.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel6.setText("ThreePointAttempts");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jtxtThreePointAttempts.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jPanel2.add(jtxtThreePointAttempts, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 380, -1));

        jScrollPane1.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N

        jTable1.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Player", "Number", "FTA", "FTM", "FT_Percentage", "3PointAttempts", "3PointMade", "3PointPercentage"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 1090, 330));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel7.setText("Number");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        jTextField6.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jTextField6.setText("jTextField1");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 380, -1));

        jTextField7.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jTextField7.setText("jTextField1");
        jPanel2.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 380, -1));

        jLabel9.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        jLabel9.setText("ThreePointMade");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, -1, -1));

        jtxtThreePointMade.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jtxtThreePointMade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtThreePointMadeActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtThreePointMade, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 380, -1));

        jLabel10.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel10.setText("ThreePoint_Percentage ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, -1, -1));

        jtxtThreePoint_Percentage.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jPanel2.add(jtxtThreePoint_Percentage, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 380, -1));

        jLabel11.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jLabel11.setText("Player");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        jtxtPlayer.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jtxtPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPlayerActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 380, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 1120, 750));

        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 255), 4));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 260, 630));

        jbtnUpdate.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jbtnUpdate.setText("Update");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 200, -1));

        jbtnAdd.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jbtnAdd.setText("Add New ");
        jbtnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAddActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 200, -1));

        jbtnReset.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jbtnReset.setText("Reset");
        jbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnResetActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 200, -1));

        jbtnDelete.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jbtnDelete.setText("Delete");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 200, -1));

        jbtnExit.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        jbtnExit.setText("Exit");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 200, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 140, 240, 610));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Cambay Devanagari", 1, 55)); // NOI18N
        jLabel1.setText("Basketball Stats Tracker");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, 710, 60));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1380, 110));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 1410, 930));
    }// </editor-fold>//GEN-END:initComponents

    // ADD Action
    
    private void jbtnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAddActionPerformed
        try {
            Class.forName("com.mysql.jdbc.Driver");
            sqlConn = DriverManager.getConnection(dataConn, username, password);
            pst = sqlConn.prepareStatement("INSERT INTO PlayerStats (Player, Number, FTA, FTM, FT_Percentage, ThreePointAttempts, ThreePointMade, ThreePoint_Percentage) VALUE(?,?,?,?,?,?,?,?)");
            pst.setString(1, jtxtPlayer.getText());
            pst.setString(2, jtxtNumber.getText());
            pst.setString(3, jtxtFTA.getText());
            pst.setString(4, jtxtFTM.getText());
            pst.setString(5, jtxtFT_Percentage.getText());
            pst.setString(6, jtxtThreePointAttempts.getText());
            pst.setString(7, jtxtThreePointMade.getText());
            pst.setString(8, jtxtThreePoint_Percentage.getText());

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Added");
            upDateDB();

        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "SQL Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Class not found: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Close resources in the finally block
            try {
                if (pst != null) {
                    pst.close();
                }
                if (sqlConn != null) {
                    sqlConn.close();
                }
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jbtnAddActionPerformed

    private void jtxtNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNumberActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jtxtPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPlayerActionPerformed

    private void jtxtFT_PercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFT_PercentageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFT_PercentageActionPerformed

    private void jtxtFTMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFTMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFTMActionPerformed

    private void jtxtThreePointMadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtThreePointMadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtThreePointMadeActionPerformed
    private JFrame frame;

    // EXIT Action
    
    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame("Exit");
        if (JOptionPane.showConfirmDialog(frame, "Confirm Exit?", "Basketball Tracker", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    // RESET Action
    
    private void jbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnResetActionPerformed
        jtxtFTA.setText("");
        jtxtFTM.setText("");
        jtxtFT_Percentage.setText("");
        jtxtNumber.setText("");
        jtxtPlayer.setText("");
        jtxtThreePointAttempts.setText("");
        jtxtThreePointMade.setText("");
        jtxtThreePoint_Percentage.setText("");
    }//GEN-LAST:event_jbtnResetActionPerformed

    // !!!!!!!!!!!!!!!!!!!!!!! UPDATE Action !!!!!!!!!!!!!!!!!!!!!!!
    
    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed
         try {
        Class.forName("com.mysql.jdbc.Driver");
        sqlConn = DriverManager.getConnection(dataConn, username, password);
        int selectedRow = jTable1.getSelectedRow(); // Get the selected row
        if (selectedRow != -1) { // Check if a row is selected
            id = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString()); // Get the ID from the first column

            pst = sqlConn.prepareStatement("update PlayerStats set Player = ?, Number = ?, FTA = ?,  FTM = ?, FT_Percentage = ?, ThreePointAttempts = ?, ThreePointMade = ?, ThreePoint_Percentage = ? where ID = ?");
            pst.setString(1, jtxtPlayer.getText());
            pst.setString(2, jtxtNumber.getText());
            pst.setString(3, jtxtFTA.getText());
            pst.setString(4, jtxtFTM.getText());
            pst.setString(5, jtxtFT_Percentage.getText());
            pst.setString(6, jtxtThreePointAttempts.getText());
            pst.setString(7, jtxtThreePointMade.getText());
            pst.setString(8, jtxtThreePoint_Percentage.getText());
            pst.setInt(9, id); // Set the ID value

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Record Updated");
            upDateDB();
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row to update.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "SQL Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } catch (ClassNotFoundException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Class not found: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        // Close resources in the finally block
        try {
            if (pst != null) {
                pst.close();
            }
            if (sqlConn != null) {
                sqlConn.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }                

    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        DefaultTableModel RecordTable = (DefaultTableModel) jTable1.getModel();
         int SelectedRows = jTable1.getSelectedRow();  
        jtxtPlayer.setText(RecordTable.getValueAt(SelectedRows, 1).toString());
        jtxtNumber.setText(RecordTable.getValueAt(SelectedRows, 2).toString());
        jtxtFTA.setText(RecordTable.getValueAt(SelectedRows, 3).toString());
        jtxtFTM.setText(RecordTable.getValueAt(SelectedRows, 4).toString());
        jtxtFT_Percentage.setText(RecordTable.getValueAt(SelectedRows, 5).toString());
        jtxtThreePointAttempts.setText(RecordTable.getValueAt(SelectedRows, 6).toString());
        jtxtThreePointMade.setText(RecordTable.getValueAt(SelectedRows, 7).toString());
        jtxtThreePoint_Percentage.setText(RecordTable.getValueAt(SelectedRows, 8).toString());
         
    }//GEN-LAST:event_jTable1MouseClicked

    // DELETE Action
    
    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
  try {
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int id = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());

        // Execute the DELETE statement
        Class.forName("com.mysql.jdbc.Driver");
        sqlConn = DriverManager.getConnection(dataConn, username, password);
        pst = sqlConn.prepareStatement("DELETE FROM PlayerStats WHERE ID = ?");
        pst.setInt(1, id);
        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Record Deleted");
        upDateDB(); // Refresh the table

    } catch (SQLException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "SQL Error: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } catch (ClassNotFoundException ex) {
        ex.printStackTrace();
        JOptionPane.showMessageDialog(this, "Class not found: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    } finally {
        // Close resources in the finally block
        try {
            if (pst != null) {
                pst.close();
            }
            if (sqlConn != null) {
                sqlConn.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    
    }    }//GEN-LAST:event_jbtnDeleteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JButton jbtnAdd;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnReset;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JTextField jtxtFTA;
    private javax.swing.JTextField jtxtFTM;
    private javax.swing.JTextField jtxtFT_Percentage;
    private javax.swing.JTextField jtxtNumber;
    private javax.swing.JTextField jtxtPlayer;
    private javax.swing.JTextField jtxtThreePointAttempts;
    private javax.swing.JTextField jtxtThreePointMade;
    private javax.swing.JTextField jtxtThreePoint_Percentage;
    // End of variables declaration//GEN-END:variables
}
